apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reggeltbot
  name: reggeltbot
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reggeltbot
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: reggeltbot
    spec:
      containers:
        - env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/zal1000-20bc518d7c88.json
            - name: RAPIPORT
              value: 10.8.6.76:8080
            - name: APIURL
              value: 10.8.2.188:8080
          image: gcr.io/zal1000/github.com/zal1000/reggeltbot
          imagePullPolicy: IfNotPresent
          name: reggeltbot-1
          volumeMounts:
            - mountPath: /var/secrets/google
              name: google-cloud-key
      volumes:
        - name: google-cloud-key
          secret:
            defaultMode: 420
            secretName: firebase-key
